### ISSUE TITLE
Create Build Process

### ISSUE THREAD

**Issue by wesleyboar-fka-iosulfur** [wesleyboar/wesleyb-sample-wysiwyg-rpg-card-maker#9]
A build process will allow production-ready distributions for the results of the following issues (and any other framework implementations): 

- original plain JavaScript solution
- issue #3
- issue #5
- issue #6

**Comment by wesleyboar** [comment]
Completed via PR #10.

**Comment by wesleyboar-fka-iosulfur** [comment]
Completed via PR #10.

**Comment by wesleyboar** [comment]
**Summary**
After merging issue #3, the build process is coupled too tightly to React needs. I re-open this issue to signify my revisiting the build process.

**Tasks**

- [ ] Isolate framework build specifics from generic build process.

**Comment by wesleyboar-fka-iosulfur** [comment]
**Summary**
After merging issue #3, the build process is coupled too tightly to React needs. I re-open this issue to signify my revisiting the build process.

**Tasks**

- [ ] Isolate framework build specifics from generic build process.

**Comment by wesleyboar-fka-iosulfur** [comment]
Merged via PR #12 .
